"""create_memory_tables

Revision ID: 04b5703c10b1
Revises: a1b2c3d4e5f6
Create Date: 2026-07-10 10:53:09.414201

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04b5703c10b1"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_sessions_id"),
        "conversation_sessions",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_sessions_user_id"),
        "conversation_sessions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "memory_categories",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_memory_categories_id"), "memory_categories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_memory_categories_user_id"),
        "memory_categories",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "memory_tags",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_memory_tags_id"), "memory_tags", ["id"], unique=False)
    op.create_index(
        op.f("ix_memory_tags_user_id"), "memory_tags", ["user_id"], unique=False
    )
    op.create_table(
        "conversation_messages",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["conversation_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_messages_id"),
        "conversation_messages",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_messages_session_id"),
        "conversation_messages",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "conversation_summaries",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["conversation_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_summaries_id"),
        "conversation_summaries",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversation_summaries_session_id"),
        "conversation_summaries",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "users_memories",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("importance_score", sa.Float(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["memory_categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_memories_id"), "users_memories", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_users_memories_user_id"), "users_memories", ["user_id"], unique=False
    )
    op.create_table(
        "memory_tag_association",
        sa.Column("memory_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["memory_id"], ["users_memories.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["memory_tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("memory_id", "tag_id"),
    )
    op.create_index(op.f("ix_documents_id"), "documents", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_id"), table_name="documents")
    op.drop_table("memory_tag_association")
    op.drop_index(op.f("ix_users_memories_user_id"), table_name="users_memories")
    op.drop_index(op.f("ix_users_memories_id"), table_name="users_memories")
    op.drop_table("users_memories")
    op.drop_index(
        op.f("ix_conversation_summaries_session_id"),
        table_name="conversation_summaries",
    )
    op.drop_index(
        op.f("ix_conversation_summaries_id"), table_name="conversation_summaries"
    )
    op.drop_table("conversation_summaries")
    op.drop_index(
        op.f("ix_conversation_messages_session_id"), table_name="conversation_messages"
    )
    op.drop_index(
        op.f("ix_conversation_messages_id"), table_name="conversation_messages"
    )
    op.drop_table("conversation_messages")
    op.drop_index(op.f("ix_memory_tags_user_id"), table_name="memory_tags")
    op.drop_index(op.f("ix_memory_tags_id"), table_name="memory_tags")
    op.drop_table("memory_tags")
    op.drop_index(op.f("ix_memory_categories_user_id"), table_name="memory_categories")
    op.drop_index(op.f("ix_memory_categories_id"), table_name="memory_categories")
    op.drop_table("memory_categories")
    op.drop_index(
        op.f("ix_conversation_sessions_user_id"), table_name="conversation_sessions"
    )
    op.drop_index(
        op.f("ix_conversation_sessions_id"), table_name="conversation_sessions"
    )
    op.drop_table("conversation_sessions")
    # ### end Alembic commands ###
