"""create_vector_document_chunk_table

Revision ID: 063cdb112c1a
Revises: 587ed2638f2f
Create Date: 2026-07-10 12:31:43.546599

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "063cdb112c1a"
down_revision: str | Sequence[str] | None = "587ed2638f2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vector_document_chunks",
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vector_document_chunks_document_id"),
        "vector_document_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vector_document_chunks_id"),
        "vector_document_chunks",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vector_document_chunks_user_id"),
        "vector_document_chunks",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vector_document_chunks_user_id"), table_name="vector_document_chunks"
    )
    op.drop_index(
        op.f("ix_vector_document_chunks_id"), table_name="vector_document_chunks"
    )
    op.drop_index(
        op.f("ix_vector_document_chunks_document_id"),
        table_name="vector_document_chunks",
    )
    op.drop_table("vector_document_chunks")
    # ### end Alembic commands ###
