"""add_assistant_chats_table

Revision ID: 0f498db96e13
Revises: e7dddc7d4376
Create Date: 2026-07-10 15:30:03.734751

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f498db96e13"
down_revision: str | Sequence[str] | None = "e7dddc7d4376"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_chats",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("user_message", sa.Text(), nullable=False),
        sa.Column("assistant_message", sa.Text(), nullable=False),
        sa.Column("recommendations", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("actions", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assistant_chats_conversation_id"),
        "assistant_chats",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_chats_id"), "assistant_chats", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_assistant_chats_user_id"), "assistant_chats", ["user_id"], unique=False
    )
    op.alter_column(
        "vector_document_chunks",
        "metadata_json",
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vector_document_chunks",
        "metadata_json",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_assistant_chats_user_id"), table_name="assistant_chats")
    op.drop_index(op.f("ix_assistant_chats_id"), table_name="assistant_chats")
    op.drop_index(
        op.f("ix_assistant_chats_conversation_id"), table_name="assistant_chats"
    )
    op.drop_table("assistant_chats")
    # ### end Alembic commands ###
