"""create_embedding_cache_table

Revision ID: 587ed2638f2f
Revises: b44d0021a1d2
Create Date: 2026-07-10 11:48:55.400249

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "587ed2638f2f"
down_revision: str | Sequence[str] | None = "b44d0021a1d2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "embedding_caches",
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "text_hash", "model_name", name="uq_embedding_caches_hash_model"
        ),
    )
    op.create_index(
        op.f("ix_embedding_caches_id"), "embedding_caches", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_embedding_caches_model_name"),
        "embedding_caches",
        ["model_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_embedding_caches_text_hash"),
        "embedding_caches",
        ["text_hash"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_embedding_caches_text_hash"), table_name="embedding_caches")
    op.drop_index(op.f("ix_embedding_caches_model_name"), table_name="embedding_caches")
    op.drop_index(op.f("ix_embedding_caches_id"), table_name="embedding_caches")
    op.drop_table("embedding_caches")
    # ### end Alembic commands ###
