"""update_documents_metadata_retry

Revision ID: b44d0021a1d2
Revises: 04b5703c10b1
Create Date: 2026-07-10 11:25:40.804378

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b44d0021a1d2"
down_revision: str | Sequence[str] | None = "04b5703c10b1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents",
        sa.Column("retry_count", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "documents",
        sa.Column(
            "retries_exhausted", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.add_column("documents", sa.Column("metadata_json", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents", "metadata_json")
    op.drop_column("documents", "retries_exhausted")
    op.drop_column("documents", "retry_count")
    # ### end Alembic commands ###
