"""add_analytics_domain_models

Revision ID: e7dddc7d4376
Revises: 063cdb112c1a
Create Date: 2026-07-10 14:59:08.861111

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7dddc7d4376"
down_revision: str | Sequence[str] | None = "063cdb112c1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_budgets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("monthly_limit", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_budgets_id"), "analytics_budgets", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_budgets_user_id"),
        "analytics_budgets",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "analytics_expenses",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("expense_date", sa.Date(), nullable=False),
        sa.Column("is_recurring", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_expenses_category"),
        "analytics_expenses",
        ["category"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_expenses_expense_date"),
        "analytics_expenses",
        ["expense_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_expenses_id"), "analytics_expenses", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_expenses_user_id"),
        "analytics_expenses",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "analytics_goals",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "completed", "paused", "abandoned", name="goalstatus"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("progress_pct", sa.Float(), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("is_quarterly", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_goals_id"), "analytics_goals", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_goals_status"), "analytics_goals", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_goals_user_id"), "analytics_goals", ["user_id"], unique=False
    )
    op.create_table(
        "analytics_habits",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "frequency",
            sa.Enum("DAILY", "WEEKLY", name="habitfrequency"),
            nullable=False,
        ),
        sa.Column("completions", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("longest_streak", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("color", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_habits_id"), "analytics_habits", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_habits_user_id"),
        "analytics_habits",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "analytics_tasks",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "OVERDUE", "CANCELLED", name="taskstatus"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_tasks_due_date"),
        "analytics_tasks",
        ["due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_tasks_id"), "analytics_tasks", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_tasks_status"), "analytics_tasks", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_analytics_tasks_user_id"), "analytics_tasks", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analytics_tasks_user_id"), table_name="analytics_tasks")
    op.drop_index(op.f("ix_analytics_tasks_status"), table_name="analytics_tasks")
    op.drop_index(op.f("ix_analytics_tasks_id"), table_name="analytics_tasks")
    op.drop_index(op.f("ix_analytics_tasks_due_date"), table_name="analytics_tasks")
    op.drop_table("analytics_tasks")
    op.drop_index(op.f("ix_analytics_habits_user_id"), table_name="analytics_habits")
    op.drop_index(op.f("ix_analytics_habits_id"), table_name="analytics_habits")
    op.drop_table("analytics_habits")
    op.drop_index(op.f("ix_analytics_goals_user_id"), table_name="analytics_goals")
    op.drop_index(op.f("ix_analytics_goals_status"), table_name="analytics_goals")
    op.drop_index(op.f("ix_analytics_goals_id"), table_name="analytics_goals")
    op.drop_table("analytics_goals")
    op.drop_index(
        op.f("ix_analytics_expenses_user_id"), table_name="analytics_expenses"
    )
    op.drop_index(op.f("ix_analytics_expenses_id"), table_name="analytics_expenses")
    op.drop_index(
        op.f("ix_analytics_expenses_expense_date"), table_name="analytics_expenses"
    )
    op.drop_index(
        op.f("ix_analytics_expenses_category"), table_name="analytics_expenses"
    )
    op.drop_table("analytics_expenses")
    op.drop_index(op.f("ix_analytics_budgets_user_id"), table_name="analytics_budgets")
    op.drop_index(op.f("ix_analytics_budgets_id"), table_name="analytics_budgets")
    op.drop_table("analytics_budgets")
    # ### end Alembic commands ###
